### ISSUE TITLE
Feature request: bookmark links

### ISSUE THREAD

**Issue by v-iashin** [ekarbe/rss-reader#5]
It would be nice to have the opportunity to bookmark some links.

**Comment by ekarbe** [comment]
This would be a pretty big enhancement. My first idea would be to have a dropdown with which you can access the bookmarks and a context menu entry to add/remove entries:

![Screenshot_20191224_205929](https://user-images.githubusercontent.com/38853513/71424294-92e74e80-2690-11ea-9ac8-7e01a66f5cbf.png)
![Screenshot_20191224_210210](https://user-images.githubusercontent.com/38853513/71424297-967ad580-2690-11ea-8a0e-c01ff3fd584c.png)

But I have to think about it because it would remove some simplicity of the extension.

**Comment by v-iashin** [comment]
I was also thinking about a similar tab as you have in the `Explorer` tab. Specifically, it has `Open Editors`, `Current Folder`, and `Outline`. Similarly, the `RSSReader` tab could have `Feed` and `Bookmarks` similarly to the second image you showed.

**Comment by ekarbe** [comment]
@v-iashin same as #6 : Look at [vscode-rss](https://github.com/luyuhuang/vscode-rss) from @luyuhuang for this feature.
